### ISSUE TITLE
[ADD] Share your Vault option

### ISSUE THREAD

**Issue by realpaaao** [vultisig/airdrop-registry#37]
That users and DAOs can share their vault easily please implement a share option
![image](https://github.com/user-attachments/assets/daf4bab4-402a-4fe3-8169-7598613420a8)

When pressing `share your vault` it automatically copies the vault url to the clipboard and gives a pop-up message `Copied to clipboard`

URL example : `https://web.vultisig.com/02d9c45007ddbaffdcad516275785e8716e9a036993b8e337b9c43f1937322b9a3/aa300bb2e508db9825f14ae3cca962ddaa139b2791e5bc230c746835a27f3e83`

**Comment by Ehsan-saradar** [comment]
Moved to https://github.com/vultisig/vultisig-web/issues/4
