### ISSUE TITLE
[ADD] Rename Vault and Vault settings

### ISSUE THREAD

**Issue by realpaaao** [vultisig/airdrop-registry#40]
For this feature we added more pages on [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=13071-3022&t=YHt2A8bLLWhhSBFJ-4) to be able to rename and remove a vault.

**Comment by Ehsan-saradar** [comment]
Moved to https://github.com/vultisig/vultisig-web/issues/5
